server:
  port: 8080
  servlet:
    context-path: /step-project-se
spring:
  main:
    banner-mode: off
  application:
    name: step-project-se
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false
    username: root
    password: root
  profiles:
    include: actuator