management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: false
    info:
      enabled: true