apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back-deployment
  namespace: phonebook-app
  labels:
    app: app-back
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
        tier: backend
        track: stable
    spec:
      containers:
        - name: app-back
          image: Arzu1996/backend
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql_db:3306/mysql?useSSL=false
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /app/config
              name: backend-config
      restartPolicy: Always
      volumes:
        - name: backend-config
          configMap:
            name: backend-config
            kubectl set image deployment/app-back-deployment app-back=Arzu1996/backend